### ISSUE TITLE
Fatal error with authorization

### ISSUE THREAD

**Issue by aimeos** [thephpleague/omnipay-dummy#2]
We get a fatal error now in our Omnipay tests when using the Dummy gateway in combination with authorization:

Fatal error: Call to a member function validate() on a non-object in aimeos-core/vendor/omnipay/dummy/src/Message/AuthorizeRequest.php on line 16

The is most likely caused by this change:
https://github.com/thephpleague/omnipay-dummy/blob/master/src/Message/AuthorizeRequest.php#L16

**Comment by barryvdh** [comment]
Since when? Cause that hasn't change in like two years..

**Comment by aimeos** [comment]
Sorry, wrong link. This is the change that is likely causing the problem:
https://github.com/thephpleague/omnipay-common/commit/3c1efd07af3fc823636149cfabca835b0f871138

**Comment by barryvdh** [comment]
What is the input of the key?

**Comment by judgej** [comment]
The kind of change where it highlights what was thought to have been a null somewhere, turns out to be an empty string or 0.

**Comment by aimeos** [comment]
The result is that it doesn't throw an exception any more but it's not checked if the return value is a valid object.

**Comment by delatbabel** [comment]
Merged omnipay-common#81
